import { AppSidebar } from '@/components/appSiderbar'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata = {
  title: 'Admin - Gerenciador de Torneios',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main>
        <SidebarTrigger />
        {children}
      </main>
    </SidebarProvider>
  )
}
