name: 'Ping Server'

on:
  workflow_dispatch:
  schedule:
    # Access https://crontab.guru/ to setup the cron string
    # America/Sao_Paulo (GMT-3). 10-20 (UTC) = 7-17 (GMT-3)
    - cron: '*/12 10-20 * * 1-5' 

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Display date time
        run: date
      - name: Ping server
        run: curl https://gerenciador-torneio.onrender.com/api/ping
