name: 'Ping Server'

on:
  workflow_dispatch:
  schedule:
    - cron: '*/12 10-20 * * 1-5'

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Display date time
        run: date
      - name: Ping server
        run: curl https://gerenciador-torneio.onrender.com/api/ping
